name: "Build"

on:
    push:
    pull_request:
jobs:
    build:
        name: Build (Windows)

        permissions:
            actions: read
            contents: read
            security-events: write

        strategy:
            fail-fast: false
            matrix:
                os: [windows-latest, ubuntu-latest]
        runs-on: ${{ matrix.os }}

        steps:
            - name: "Checkout"
              uses: actions/checkout@v3

            - name: "Install Node"
              uses: actions/setup-node@v3

            - name: "Install packages"
              if: matrix.os == 'ubuntu-latest'
              run: |
                  sudo apt-get update -y && sudo apt-get upgrade -y
                  sudo apt-get install wine -y
                  dpkg --add-architecture i386 && apt-get update &&
                  sudo apt-get install wine32 -y
                  sudo apt-get install rpm -y

            - name: Install and build
              run: |
                  npm ci
                  npm run build
