name: "Build"

on:
    push:
    pull_request:
jobs:
    build:
        name: Build (Windows)

        permissions:
            actions: read
            contents: read
            security-events: write

        strategy:
            fail-fast: false
            matrix:
                os: [windows-latest]
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
            - name: Install and build
              run: |
                  npm ci
                  npm run build

            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                  files: dist/*.zip
                  tag_name: nightly
                  fail_on_unmatched_files: true
                  name: Nightly build
                  prerelease: true
                  body: "Latest commit build."
