name: "Build"

on:
    push:
    pull_request:
jobs:
    build:
        name: Build (Windows)

        permissions:
            actions: read
            contents: read
            security-events: write

        strategy:
            fail-fast: false
            matrix:
                os: [windows-latest, ubuntu-latest]
        runs-on: ${{ matrix.os }}

        steps:
            - name: "Checkout"
              uses: actions/checkout@v3

            - name: "Install node"
              uses: actions/setup-node@v3

            - name: "Install Wine"
              if: matrix.os == ubuntu-latest
              run: |
                  sudo apt install wine

            - name: Install and build
              run: |
                  npm ci
                  npm run build
